# Page settings
# See https://gohugo.io/getting-started/configuration/

baseurl = "http://localhost:1313"
title = "Fiveum"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css"]

  # Meta
  author = "Vijay Nayar"
  description = "Website for the Fiveum workplace collaboration service."
  email = "contact@funnel-labs.io"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Theme colors
  [params.colors]
    color1 = "#0d1a5c"
    color2 = "#090d2c"
    color3 = "#7f7f7f"
    color4 = "#393e46"
    color5 = "#fff"

  # Navigation
  [params.navigation]
    brand = "Fiveum"
    brandLogo = "images/FiveumLogo5.png"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    features = "Features"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = 'Fiveum'
    subtitle = 'Workplace collaboration without the noise.'
    brandLogo = "images/FiveumLogo5.png"
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Collaboration Tools"
    description = "Real-time Chat, Live Forums, Issue Tracking, Audio/Video Conferencing, Whiteboarding, Shared Files, and more."
    #url = "#"
    #button = "Get In Touch"
    icon = "icon-bubbles"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Smart Notifications"
    description = "Prioritizes notifications and avoids unnecessary interruptions by leveraging knowledge of employee reporting structures, teams, and roles within company directory services. High priority notifications get through, but lower priority notifications are given in batches, protecting important focus-time to get work done."
    #url = "#"
    #button = "Click Me"
    icon = "icon-target"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "AI Newsletters"
    description = "AI-Generated newsletters providing summaries of recent activity at different levels of abstraction such as a project, team, department, or the entire company."
    #url = "#"
    #button = "Why us?"
    icon = "icon-note"
    img = "img_10.jpg"

  #[params.intro.video]
  #  enable = true
  #  title = "Watch the video"
  #  icon = "icon-play2"
  #  url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  #[params.work]
  #  enable = true
  #  title = "Work"
  #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #  footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'
  #
  #  [[params.work.row]]
  #    img = "work_1.jpg"
  #    alt = "Image2"
  #    title = "Project 1"
  #    subtitle = "Branding"
  #
  #  [[params.work.row]]
  #    img = "work_2.jpg"
  #    alt = "Image2"
  #    title = "Project 2"
  #    subtitle = "Design"
  #
  #  [[params.work.row]]
  #    img = "work_3.jpg"
  #    alt = "Image3"
  #    title = "Project 3"
  #    subtitle = "Design"
  #
  #  [[params.work.row]]
  #    img = "work_4.jpg"
  #    alt = "Image4"
  #    title = "Project 4"
  #    subtitle = "Design"
  #
  #  [[params.work.row]]
  #    img = "work_5.jpg"
  #    alt = "Image5"
  #    title = "Project 5"
  #    subtitle = "Design"
  #
  #  [[params.work.row]]
  #    img = "work_6.jpg"
  #    alt = "Image6"
  #    title = "Project 6"
  #    subtitle = "Design"

  # Testimonials section
  #[params.testimonials]
  #  enable = true
  #  title = "Testimonials"
  #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #
  #  [[params.testimonials.item]]
  #    quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
  #    person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  #    img = "person1.jpg"
  #    alt = "Person1"
  #
  #  [[params.testimonials.item]]
  #    quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
  #    person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  #    img = "person2.jpg"
  #    alt = "Person2"
  #
  #  [[params.testimonials.item]]
  #    quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
  #    person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  #    img = "person3.jpg"
  #    alt = "Person3"


  # Features section
  [params.features]
    enable = true
    title = "Features"
    description = "Optimized for productive collaboration and focused work."

    [[params.features.item]]
      title = "Organized Topics"
      description = "Each topic in Fiveum provides access to a collaboration tool such as chat, live-forums, etc. Topics may contain other topics, which allows them to be structured in the same way people are organized in your company, whether that be in functional departments or in cross-functional teams."
      image = "images/Topics.png"

    [[params.features.item]]
      title = "Focused Communication"
      description = "Live-forum based communication is used to manage short-lived conversations that to solve a problem, including software bugs/features, sales negotiations, and customer support. Conversations have associated contextual information as well as status to help others follow along."
      image = "images/Fiveum-Live-Forums-Clipped.png"

    [[params.features.item]]
      title = "Smart Notifications"
      description = "By tapping into your company directory services, the relationships between employees, their roles, and their responsibilities are used to prioritize notifications. Priority is used to determine whether new messages should interrupt your focus or not."
      image = "images/NotificationRhythm.png"

  # Services section
  [params.services]
    enable = false
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "Interested in being an alpha customer? Have thoughts to share?"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Postfach 301610, 10748 Berlin, Germany"],
        #["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "contact@funnel-labs.io"],
        ["icon-globe", '<a href="https://fiveum.funnel-labs.io/" target="_blank">fiveum.funnel-labs.io</a>']
      ]

    actionUrl = "https://formspree.io/f/mqkoglla"
    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
